name: C Program Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v4

      - name: Set up C environment
        run: sudo apt-get install build-essential

      - name: Build the C program
        run: make

      - name: Upload build artifact
        uses: actions/upload-artifact@v3 # <-- Updated to version 3
        with:
          name: hello
          path: ./hello
